
BORDER = 12
LIGATION_SIZE = 26
ATOM_RADIUS = 7
DISTANCE_BETWEEN_LIGATIONS = 20

WAVES = {
	{ 0 },
	{ DISTANCE_BETWEEN_LIGATIONS / 2, -DISTANCE_BETWEEN_LIGATIONS / 2 },
	{ DISTANCE_BETWEEN_LIGATIONS, 0, -DISTANCE_BETWEEN_LIGATIONS }
}

ELETRONS_TYPES = {
	["-"] = 1,
	["="] = 2,
	["%"] = 3
}